// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://drgrujwjowotwnhqplmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRyZ3J1andqb3dvdHduaHFwbG1nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MzY0MzEsImV4cCI6MjA3NDMxMjQzMX0.JSGNItx3nIvJrV1hFlR9jQC_qbYkhpmLmPjRRWd7Atc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});